namespace PhysSound{
//DO NOT EDIT THIS FILE DIRECTLY! Use the editor provided under Window/PhysSound.
public class PhysSoundTypeList {
public static string[] PhysSoundTypes = new string[3] {"Hard","Soft","Other"};

public static string GetKey(int index) { return (index >= PhysSoundTypes.Length) || (index < 0) ? "" : PhysSoundTypes[index]; }

public static bool HasKey(int index) { return index < PhysSoundTypes.Length && index >= 0; }

}
}
